=begin
 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/autocompletes", type: :request do
  # Autocomplete. As you add validations to Autocomplete, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Autocomplete.create! valid_attributes
      get autocompletes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      autocomplete = Autocomplete.create! valid_attributes
      get autocomplete_url(autocomplete)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_autocomplete_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      autocomplete = Autocomplete.create! valid_attributes
      get edit_autocomplete_url(autocomplete)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Autocomplete" do
        expect {
          post autocompletes_url, params: { autocomplete: valid_attributes }
        }.to change(Autocomplete, :count).by(1)
      end

      it "redirects to the created autocomplete" do
        post autocompletes_url, params: { autocomplete: valid_attributes }
        expect(response).to redirect_to(autocomplete_url(Autocomplete.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Autocomplete" do
        expect {
          post autocompletes_url, params: { autocomplete: invalid_attributes }
        }.to change(Autocomplete, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post autocompletes_url, params: { autocomplete: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested autocomplete" do
        autocomplete = Autocomplete.create! valid_attributes
        patch autocomplete_url(autocomplete), params: { autocomplete: new_attributes }
        autocomplete.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the autocomplete" do
        autocomplete = Autocomplete.create! valid_attributes
        patch autocomplete_url(autocomplete), params: { autocomplete: new_attributes }
        autocomplete.reload
        expect(response).to redirect_to(autocomplete_url(autocomplete))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        autocomplete = Autocomplete.create! valid_attributes
        patch autocomplete_url(autocomplete), params: { autocomplete: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested autocomplete" do
      autocomplete = Autocomplete.create! valid_attributes
      expect {
        delete autocomplete_url(autocomplete)
      }.to change(Autocomplete, :count).by(-1)
    end

    it "redirects to the autocompletes list" do
      autocomplete = Autocomplete.create! valid_attributes
      delete autocomplete_url(autocomplete)
      expect(response).to redirect_to(autocompletes_url)
    end
  end
end

=end