 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/delivery_schedules", type: :request do
  # DeliverySchedule. As you add validations to DeliverySchedule, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DeliverySchedule.create! valid_attributes
      get delivery_schedules_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      delivery_schedule = DeliverySchedule.create! valid_attributes
      get delivery_schedule_url(delivery_schedule)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_delivery_schedule_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      delivery_schedule = DeliverySchedule.create! valid_attributes
      get edit_delivery_schedule_url(delivery_schedule)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DeliverySchedule" do
        expect {
          post delivery_schedules_url, params: { delivery_schedule: valid_attributes }
        }.to change(DeliverySchedule, :count).by(1)
      end

      it "redirects to the created delivery_schedule" do
        post delivery_schedules_url, params: { delivery_schedule: valid_attributes }
        expect(response).to redirect_to(delivery_schedule_url(DeliverySchedule.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DeliverySchedule" do
        expect {
          post delivery_schedules_url, params: { delivery_schedule: invalid_attributes }
        }.to change(DeliverySchedule, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post delivery_schedules_url, params: { delivery_schedule: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested delivery_schedule" do
        delivery_schedule = DeliverySchedule.create! valid_attributes
        patch delivery_schedule_url(delivery_schedule), params: { delivery_schedule: new_attributes }
        delivery_schedule.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the delivery_schedule" do
        delivery_schedule = DeliverySchedule.create! valid_attributes
        patch delivery_schedule_url(delivery_schedule), params: { delivery_schedule: new_attributes }
        delivery_schedule.reload
        expect(response).to redirect_to(delivery_schedule_url(delivery_schedule))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        delivery_schedule = DeliverySchedule.create! valid_attributes
        patch delivery_schedule_url(delivery_schedule), params: { delivery_schedule: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested delivery_schedule" do
      delivery_schedule = DeliverySchedule.create! valid_attributes
      expect {
        delete delivery_schedule_url(delivery_schedule)
      }.to change(DeliverySchedule, :count).by(-1)
    end

    it "redirects to the delivery_schedules list" do
      delivery_schedule = DeliverySchedule.create! valid_attributes
      delete delivery_schedule_url(delivery_schedule)
      expect(response).to redirect_to(delivery_schedules_url)
    end
  end
end
