 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/deliveries", type: :request do
  # Delivery. As you add validations to Delivery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Delivery.create! valid_attributes
      get deliveries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      delivery = Delivery.create! valid_attributes
      get delivery_url(delivery)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_delivery_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      delivery = Delivery.create! valid_attributes
      get edit_delivery_url(delivery)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Delivery" do
        expect {
          post deliveries_url, params: { delivery: valid_attributes }
        }.to change(Delivery, :count).by(1)
      end

      it "redirects to the created delivery" do
        post deliveries_url, params: { delivery: valid_attributes }
        expect(response).to redirect_to(delivery_url(Delivery.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Delivery" do
        expect {
          post deliveries_url, params: { delivery: invalid_attributes }
        }.to change(Delivery, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post deliveries_url, params: { delivery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested delivery" do
        delivery = Delivery.create! valid_attributes
        patch delivery_url(delivery), params: { delivery: new_attributes }
        delivery.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the delivery" do
        delivery = Delivery.create! valid_attributes
        patch delivery_url(delivery), params: { delivery: new_attributes }
        delivery.reload
        expect(response).to redirect_to(delivery_url(delivery))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        delivery = Delivery.create! valid_attributes
        patch delivery_url(delivery), params: { delivery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested delivery" do
      delivery = Delivery.create! valid_attributes
      expect {
        delete delivery_url(delivery)
      }.to change(Delivery, :count).by(-1)
    end

    it "redirects to the deliveries list" do
      delivery = Delivery.create! valid_attributes
      delete delivery_url(delivery)
      expect(response).to redirect_to(deliveries_url)
    end
  end
end
