 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/polygons", type: :request do
  # Polygon. As you add validations to Polygon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Polygon.create! valid_attributes
      get polygons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      polygon = Polygon.create! valid_attributes
      get polygon_url(polygon)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_polygon_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      polygon = Polygon.create! valid_attributes
      get edit_polygon_url(polygon)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Polygon" do
        expect {
          post polygons_url, params: { polygon: valid_attributes }
        }.to change(Polygon, :count).by(1)
      end

      it "redirects to the created polygon" do
        post polygons_url, params: { polygon: valid_attributes }
        expect(response).to redirect_to(polygon_url(Polygon.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Polygon" do
        expect {
          post polygons_url, params: { polygon: invalid_attributes }
        }.to change(Polygon, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post polygons_url, params: { polygon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested polygon" do
        polygon = Polygon.create! valid_attributes
        patch polygon_url(polygon), params: { polygon: new_attributes }
        polygon.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the polygon" do
        polygon = Polygon.create! valid_attributes
        patch polygon_url(polygon), params: { polygon: new_attributes }
        polygon.reload
        expect(response).to redirect_to(polygon_url(polygon))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        polygon = Polygon.create! valid_attributes
        patch polygon_url(polygon), params: { polygon: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested polygon" do
      polygon = Polygon.create! valid_attributes
      expect {
        delete polygon_url(polygon)
      }.to change(Polygon, :count).by(-1)
    end

    it "redirects to the polygons list" do
      polygon = Polygon.create! valid_attributes
      delete polygon_url(polygon)
      expect(response).to redirect_to(polygons_url)
    end
  end
end
