development:
  adapter: postgis
  postgis_extension: true
  schema_search_path: 'public,postgis'
  host: localhost
  encoding: unicode
  database: demo_test_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: demo_test_test
  pool: 5
  timeout: 5000

production:
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
