default: &default
  adapter: postgis
  encoding: unicode
  postgis_extension: true
  schema_search_path: 'public,postgis'
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: demo_test_development
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: demo_test_development

test:
  <<: *default
  database: demo_test_test

production:
  <<: *default
  url: <%= ENV.fetch('DATABASE_URL', '').sub(/^postgres/, "postgis") %>
  database: demo_test_production
